import Head from "next/head";
import clsx from "clsx";
import { Rubik } from "next/font/google";

const font = Rubik({
  subsets: ["latin-ext"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(font.className, "flex min-h-screen flex-col")}>
        <nav className="bg-gray-600 px-4 py-4">
          <div className="text-xl font-semibold text-white">Child App</div>
        </nav>
      </main>
    </>
  );
}
